spring:
  application:
    name: api-gatway
server:
  port: 17900
#配置eureka服务地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
zuul:
  host:
    #zuul配置
    max-per-route-connections: 50
    max-total-connections: 200
    connect-timeout-millis: 600000
    socket-timeout-millis: 600000

  #关闭重试机制
  retryable: true
  routes:
    web:
      path: /web/**
      serviceId: flowers-web
#    price:
#      path: /price/**
#      serviceId: servcie-price
  include-debug-header: true
#开启debug模式
#debug: true

