server:
  port: 8282

spring:
  application:
    name: flowers-web-manager
  datasource:
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowers?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
  devtools:
    restart:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
