server:
  port: 8080

  debug: true

spring:
  application:
    name: flowers-web-flower
  datasource:
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowers?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
  devtools:
    restart:
      enabled: true
  session:
    store-type: redis
  redis:
    host: localhost
    password: redis
    port: 6379
    # 配置rabbitMQspring:
#  rabbitmq:
#    host: 127.0.0.1
#    username: guest
#    password: guest
#    virtual-host: flowers-web-flower

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#spring.resources.static-locations: classpath:/pages/
