server:
  port: 8080

  debug: true

spring:
  application:
    name: flowers-web-flower
  devtools:
    restart:
      enabled: true
    # 配置rabbitMQspring:
#  rabbitmq:
#    host: 127.0.0.1
#    username: guest
#    password: guest
#    virtual-host: flowers-web-flower

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#spring.resources.static-locations: classpath:/pages/
