server:
  port: 8090

#debug: true

spring:
  application:
    name: cloud-producer
  datasource:
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowers?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
  devtools:
    restart:
      enabled: true


mybatis:
#  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.flowers.api.model

mybatis.configuration.map-underscore-to-camel-case: true



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

