server:
  port: 8181
  servlet:
    session:
      timeout: 100m
  #debug: true

spring:
  application:
    name: flowers-web-user
  datasource:
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowers?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
  devtools:
    restart:
      enabled: true
  session:
    store-type: redis
#    redis:
#      flush-mode: on_save
#      namespace: spring: session
  redis:
    host: localhost
    password: redis
    port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#spring.resources.static-locations: classpath:/pages/



