server:
  port: 8181

  #debug: true

spring:
  application:
    name: flowers-web-user
  devtools:
    restart:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#spring.resources.static-locations: classpath:/pages/
